name: live_report
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - conda-forge::matplotlib
  - reportlab
  - scipy
  - mrcfile
  - scikit-image
  - pypdf
  - ipykernel
  - ghostscript
